local ProgressionUtils = {}

-- Imports
local Quests = require(script.Quests)
local Scores = require(script.Scores)
local Boosters = require(script.Boosters)
local Inventory = require(script.Inventory)
local RandomRewards = require(script.RandomRewards)
local TimedRewards = require(script.TimedRewards)
local Trading = require(script.Trading)

ProgressionUtils.Quests = Quests
ProgressionUtils.Scores = Scores
ProgressionUtils.Boosters = Boosters
ProgressionUtils.Inventory = Inventory
ProgressionUtils.TimedRewards = TimedRewards
ProgressionUtils.Trading = Trading
ProgressionUtils.RandomRewards = RandomRewards

return ProgressionUtils